ALTER TABLE students
ADD COLUMN gender VARCHAR(20) NULL,
ADD COLUMN dob DATE NULL,
ADD COLUMN father_name VARCHAR(100) NULL,
ADD COLUMN mother_name VARCHAR(100) NULL,
ADD COLUMN aadhaar VARCHAR(20) NULL,
ADD COLUMN disabilities TEXT NULL;
